# version: '3'

networks:
  kafka-network:
    driver: bridge
  ms2-db_network:
    driver: bridge
  ms4-db_network:
    driver: bridge
  api-network:
    driver: bridge
  ms4-api-network:
    driver: bridge
volumes:
  ms2-data:
  ms4-data:

services:

  frontend:
    build: ./front/
    env_file:
      - ./front/.env
    ports:
      - '3000:3000'
    networks:
      - ms4-api-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    networks:
      - kafka-network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  api:
    build: ./api/
    networks:
      - api-network
    ports:
      - '8000:8000'
    volumes:
      - ./api/data:/app/data


  ms1:
    build: ./ms1/
    networks:
      - kafka-network
      - api-network
    depends_on:
      - kafka
    env_file:
      - ./ms1/.env

  ms2:
    build: ./ms2/
    networks:
      - kafka-network
      - ms2-db_network
    depends_on:
      - kafka
    env_file:
      - ./ms2/.env

  ms2-db:
    image: postgres:latest
    networks:
      - ms2-db_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms2
    volumes:
      - ms2-data:/var/lib/postgresql/data
    
  ms4:
    build: ./ms4/
    networks:
      - kafka-network
      - ms4-db_network
      - ms4-api-network
    depends_on:
      - kafka
    env_file:
      - ./ms4/.env
    ports:
      - '8001:8001'

  ms4-db:
    image: postgres:latest
    networks:
      - ms4-db_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms4
    volumes:
      - ms4-data:/var/lib/postgresql/data

  ms2-db-admin:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: chris.lee@finetune.life
      PGADMIN_DEFAULT_PASSWORD: aaaa1111
    volumes:
      - ms2-data:/var/lib/pgadmin
    networks:
      - ms2-db_network

  ms4-db-admin:
    image: adminer
    restart: always
    ports:
      - 8084:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: chris.lee@finetune.life
      PGADMIN_DEFAULT_PASSWORD: aaaa1111
    volumes:
      - ms4-data:/var/lib/pgadmin
    networks:
      - ms4-db_network


