# version: '3'

networks:
  kafka-network:
    driver: bridge
  ms2-db_network:
    driver: bridge
  ms4-db_network:
    driver: bridge
  api-network:
    driver: bridge


services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    networks:
      - kafka-network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  api:
    build: ./api/
    networks:
      - api-network
    # restart: on-failure
    ports:
      - '8000:8000'
    volumes:
      - ./api/data:/app/data


  ms1:
    build: ./ms1/
    networks:
      - kafka-network
      - api-network
    depends_on:
      - kafka
    # restart: on-failure
    env_file:
      - ./ms1/.env

  ms2:
    build: ./ms2/
    networks:
      - kafka-network
      - ms2-db_network
    depends_on:
      - kafka
    # restart: on-failure
    env_file:
      - ./ms2/.env

  ms2-db:
    image: postgres:latest
    networks:
      - ms2-db_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms2
    
  ms3:
    build: ./ms3/
    networks:
      - kafka-network
      # - ms3-db_network
    depends_on:
      - kafka
    # restart: on-failure
    env_file:
      - ./ms3/.env
  ms4:
    build: ./ms4/
    networks:
      - kafka-network
      - ms4-db_network
    depends_on:
      - kafka
    # restart: on-failure
    env_file:
      - ./ms4/.env
    ports:
      - '8001:8001'

  ms4-db:
    image: postgres:latest
    networks:
      - ms4-db_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms4
    
  # ms3-db-admin:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: chris.lee@finetune.life
  #     PGADMIN_DEFAULT_PASSWORD: aaaa1111
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - ms3-db_network



# volumes:
#   pgadmin-data:
  # # db-collection:
  # #   image: postgres:latest
  # #   networks:
  # #     - app-tier
  # #   environment:
  # #     POSTGRES_USER: user
  # #     POSTGRES_PASSWORD: password
  # #     POSTGRES_DB: collection

  # # db-analysis:
  # #   image: postgres:latest
  # #   networks:
  # #     - app-tier
  # #   environment:
  # #     POSTGRES_USER: user
  # #     POSTGRES_PASSWORD: password
  # #     POSTGRES_DB: analysis