apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_SERVER_URL
                  name: frontend-env
          image: gcr.io/mathminds-418514/frontend-image
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
