apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ms2
  name: ms2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: ms2
    spec:
      containers:
        - env:
            - name: ACTIVE_SERVICES_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: ACTIVE_SERVICES_TOPIC
                  name: ms2-env
            - name: COLLECTION_KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: COLLECTION_KAFKA_TOPIC
                  name: ms2-env
            - name: DATA_PROVIDER_MAPPER_KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: DATA_PROVIDER_MAPPER_KAFKA_TOPIC
                  name: ms2-env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: ms2-env
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: ms2-env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: ms2-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: ms2-env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: ms2-env
            - name: NEW_SERVICES_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: NEW_SERVICES_TOPIC
                  name: ms2-env
            - name: REVOKED_DATA_PROVIDERS_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: REVOKED_DATA_PROVIDERS_TOPIC
                  name: ms2-env
            - name: SERVICE_MAPPER_KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: SERVICE_MAPPER_KAFKA_TOPIC
                  name: ms2-env
          image: gcr.io/mathminds-418514/ms2-image
          name: ms2
      restartPolicy: Always
